<?php
defined('BASEPATH') OR exit('No direct script access allowed');

// Extended error code
class E extends _E{

    const CAMPAIGN_PIN_HIGHLIGHT_EXCEED_LIMIT = 6001;
}

// Standard error code
class _E{
    const SUCCESS = 200;
    const HTTP_NOT_FOUND = 404;
    const HTTP_SERVICE_UNAVAILABLE = 503;

    // 1xxx Require parameter / Require value
    const REQUIRE_PARAMETER = 1001;
    const REQUIRE_PARAMETER_ID_USER = 1002;
    const REQUIRE_PARAMETER_ID_ADMIN = 1003;
    const REQUIRE_PARAMETER_ID_CONTENT = 1004;
    const REQUIRE_PARAMETER_LANG = 1005;
    const REQUIRE_PARAMETER_PAGE = 1006;
    const REQUIRE_PARAMETER_PER_PAGE = 1007;
    const REQUIRE_PARAMETER_USERNAME = 1008;
    const REQUIRE_PARAMETER_PASSWORD = 1009;
    const REQUIRE_PARAMETER_EMAIL = 1010;
    const REQUIRE_PARAMETER_TOKEN = 1011;

    const REQUIRE_VALUE = 1101;
    const REQUIRE_VALUE_ID_USER = 1102;
    const REQUIRE_VALUE_ID_ADMIN = 1103;
    const REQUIRE_VALUE_ID_CONTENT = 1104;
    const REQUIRE_VALUE_LANG = 1105;
    const REQUIRE_VALUE_PAGE = 1106;
    const REQUIRE_VALUE_PER_PAGE = 1107;
    const REQUIRE_VALUE_USERNAME = 1108;
    const REQUIRE_VALUE_PASSWORD = 1109;
    const REQUIRE_VALUE_EMAIL = 1110;
    const REQUIRE_VALUE_TOKEN = 1111;

    const REQUIRE_METHOD_GET = 1201;
    const REQUIRE_METHOD_POST = 1202;
    const REQUIRE_METHOD_HEAD = 1203;
    const REQUIRE_METHOD_PUT = 1204;
    const REQUIRE_METHOD_DELETE = 1205;
    const REQUIRE_METHOD_CONNECT = 1206;
    const REQUIRE_METHOD_OPTIONS = 1207;
    const REQUIRE_METHOD_TRACE = 1208;
    const REQUIRE_METHOD_PATCH = 1209;

    // 2xxx Invalid data type / Invalid format
    const INVALID_DATA_TYPE_CHAR = 2001;
    const INVALID_DATA_TYPE_STRING = 2002;
    const INVALID_DATA_TYPE_INT = 2003;
    const INVALID_DATA_TYPE_LONG = 2004;
    const INVALID_DATA_TYPE_FLOAT = 2005;
    const INVALID_DATA_TYPE_DOUBLE = 2006;
    const INVALID_DATA_TYPE_BOOLEAN = 2007;
    const INVALID_DATA_TYPE_ARRAY = 2008;
    const INVALID_DATA_TYPE_OBJECT = 2009;
    const INVALID_DATA_TYPE_JSON = 2010;
    const INVALID_DATA_TYPE_FILE = 2011;

    const INVALID_FORMAT = 2100;
    const INVALID_FORMAT_EMAIL = 2101;
    const INVALID_FORMAT_DATE = 2102;
    const INVALID_FORMAT_TIME = 2103;
    const INVALID_FORMAT_DATETIME = 2104;
    const INVALID_FORMAT_TEL = 2105;
    const INVALID_FORMAT_LANG = 2106;
    const INVALID_FORMAT_TOKEN = 2107;
    const INVALID_FORMAT_ORDER = 2108;

    const DUPLICATE_DATA = 2201;
    const DUPLICATE_DATA_ID = 2202;
    const DUPLICATE_DATA_EMAIL = 2203;
    const DUPLICATE_DATA_TEL = 2204;
    const DUPLICATE_DATA_USERNAME = 2205;
    const DUPLICATE_DATA_CODE = 2206;
    const DUPLICATE_DATA_SLUG = 2207;

    //3xxx Authentication
    // const AUTH_LOGIN_EMAIL_NOT_EXIST = 3001;
    // const AUTH_LOGIN_USERNAME_NOT_EXIST = 3002;
    // const AUTH_LOGIN_FACEBOOK_ID_NOT_EXIST = 3003;
    // const AUTH_LOGIN_WRONG_PASSWORD = 3004;
    const AUTH_LOGIN_ACCOUNT_NOT_VERIFIED = 3005;
    const AUTH_LOGIN_ACCOUNT_BLOCKED = 3006;
    const AUTH_LOGIN_ACCOUNT_CANNOT_NOW = 3007;
    const AUTH_LOGIN_INVALID_USERNAME_OR_PASSWORD = 3008;

    const AUTH_REGISTER_EMAIL_EXIST = 3101;
    const AUTH_REGISTER_USERNAME_EXIST = 3102;
    const AUTH_REGISTER_FACEBOOK_ID_EXIST = 3103;
    // const AUTH_REGISTER_EMAIL_SAME_FACEBOOK_EMAIL = 3104;
    const AUTH_REGISTER_PASSWORD_WEAK = 3105;
    const AUTH_REGISTER_PASSWORD_INVALID = 3106;
    const AUTH_REGISTER_PASSWORD_NOT_MATCH = 3107;
    const AUTH_REGISTER_VERIFY_EMAIL = 3108;
    const AUTH_REGISTER_CANNOT_NOW = 3109;
    const AUTH_REGISTER_TEL_EXIST = 3110;
    const AUTH_REGISTER_NAME_EXIST = 3111;

    // const AUTH_FORGOT_PASSWORD_EMAIL_NOT_EXIST = 3201;
    // const AUTH_FORGOT_PASSWORD_USERNAME_NOT_EXIST = 3202;
    const AUTH_FORGOT_PASSWORD_REQUEST_SENT = 3203;
    const AUTH_FORGOT_PASSWORD_CANNOT_NOW = 3204;

    const AUTH_RESET_PASSWORD_REQUIRE_KEY = 3301;
    const AUTH_RESET_PASSWORD_INVALID_KEY = 3302;
    const AUTH_RESET_PASSWORD_PASSWORD_WEAK = 3303;
    const AUTH_RESET_PASSWORD_PASSWORD_INVALID = 3304;
    const AUTH_RESET_PASSWORD_PASSWORD_NOT_MATCH = 3305;
    const AUTH_RESET_PASSWORD_CANNOT_NOW = 3306;

    const AUTH_CHANGE_PASSWORD_REQUIRE_TOKEN = 3401;
    const AUTH_CHANGE_PASSWORD_INVALID_TOKEN = 3402;
    const AUTH_CHANGE_PASSWORD_REQUIRE_ACCOUNT_ID = 3403;
    const AUTH_CHANGE_PASSWORD_INVALID_ACCOUNT_ID = 3404;
    const AUTH_CHANGE_PASSWORD_REQUIRE_OLD_PASSWORD = 3405;
    const AUTH_CHANGE_PASSWORD_INVALID_OLD_PASSWORD = 3406;
    const AUTH_CHANGE_PASSWORD_PASSWORD_WEAK = 3407;
    const AUTH_CHANGE_PASSWORD_PASSWORD_INVALID = 3408;
    const AUTH_CHANGE_PASSWORD_PASSWORD_NOT_MATCH = 3409;
    const AUTH_CHANGE_PASSWORD_CANNOT_NOW = 3410;

    const AUTH_MODULE_NOT_LOADED = 3501;

    // 4xxx Upload
    const UPLOAD_IMAGE_REQUIRE_BASE64 = 4001;
    const UPLOAD_IMAGE_INVALID_EXTENSION = 4002;
    const UPLOAD_IMAGE_INVALID_RESOLUTION = 4003;
    const UPLOAD_IMAGE_SIZE_EXCEED_LIMIT = 4004;
    const UPLOAD_IMAGE_CANNOT_NOW = 4005;

    const UPLOAD_FILE_INVALID_EXTENSION = 4101;
    const UPLOAD_FILE_SIZE_EXCEED_LIMIT = 4102;
    const UPLOAD_FILE_CANNOT_NOW = 4103;
    const UPLOAD_FILE_INVALID_DATA = 4104;

    // 5xxx Not found / Permission / Form submit
    const NOT_FOUND = 5001;
    const NOT_FOUND_LANG = 5002;
    const NOT_FOUND_CONTENT = 5003;
    const NOT_FOUND_ACCOUNT = 5004;
    const NOT_FOUND_TOKEN = 5005;

    const PERMISSION = 5101;
    const PERMISSION_DENIED = 5102;
    const PERMISSION_TOKEN_EXPIRE = 5103;

    const FORM_SUBMIT_FAILED = 5200;
    const FORM_SUBMIT_FAILED_CREATE = 5201;
    const FORM_SUBMIT_FAILED_UPDATE = 5202;
    const FORM_SUBMIT_FAILED_DELETE = 5203;
}

$config['error_code_loaded'] = TRUE;
